"use strict";
const name = "Генератор захисного поля";
console.log(name);
let price;
console.log(price);
price = 1000;
console.log(price);
console.log(`Обрано ${name}, ціна за штуку ${price} кредитів`);
price = 2000;
console.log(price);
console.log(`Обрано ${name}, ціна за штуку ${price} кредитів`);